# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alix/Documents/github/flappy-bird-renderer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alix/Documents/github/flappy-bird-renderer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alix/Documents/github/flappy-bird-renderer/CMakeFiles /Users/alix/Documents/github/flappy-bird-renderer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alix/Documents/github/flappy-bird-renderer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flappy-bird-renderer

# Build rule for target.
flappy-bird-renderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flappy-bird-renderer
.PHONY : flappy-bird-renderer

# fast build rule for target.
flappy-bird-renderer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/build
.PHONY : flappy-bird-renderer/fast

src/bird.o: src/bird.cpp.o
.PHONY : src/bird.o

# target to build an object file
src/bird.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/bird.cpp.o
.PHONY : src/bird.cpp.o

src/bird.i: src/bird.cpp.i
.PHONY : src/bird.i

# target to preprocess a source file
src/bird.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/bird.cpp.i
.PHONY : src/bird.cpp.i

src/bird.s: src/bird.cpp.s
.PHONY : src/bird.s

# target to generate assembly for a file
src/bird.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/bird.cpp.s
.PHONY : src/bird.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pipes.o: src/pipes.cpp.o
.PHONY : src/pipes.o

# target to build an object file
src/pipes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/pipes.cpp.o
.PHONY : src/pipes.cpp.o

src/pipes.i: src/pipes.cpp.i
.PHONY : src/pipes.i

# target to preprocess a source file
src/pipes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/pipes.cpp.i
.PHONY : src/pipes.cpp.i

src/pipes.s: src/pipes.cpp.s
.PHONY : src/pipes.s

# target to generate assembly for a file
src/pipes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/pipes.cpp.s
.PHONY : src/pipes.cpp.s

src/window.o: src/window.cpp.o
.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flappy-bird-renderer.dir/build.make CMakeFiles/flappy-bird-renderer.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... flappy-bird-renderer"
	@echo "... src/bird.o"
	@echo "... src/bird.i"
	@echo "... src/bird.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pipes.o"
	@echo "... src/pipes.i"
	@echo "... src/pipes.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

